# Generated by Django 3.2 on 2021-04-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
