# Generated by Django 3.2 on 2021-04-28 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210428_1132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
