# Generated by Django 3.2 on 2021-04-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_delete_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authors',
            new_name='author',
        ),
    ]
