# Generated by Django 3.2 on 2021-04-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
